version: "3.8"

services:
  api:
    build:
      context: .
      target: production-server
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./run/clusters
        target: /home/mcu/clusters
      - type: bind
        source: ./run/configuration.json
        target: /home/mcu/configuration.json
        read_only: true
      - type: bind
        source: ./run/acme_key.pem
        target: /home/mcu/credentials/acme_key.pem
      - type: bind
        source: ./run/clouds.yaml
        target: /home/mcu/credentials/clouds.yaml
        read_only: true
      - type: volume
        source: database
        target: /home/mcu/database
      - type: volume
        source: terraform-plugin-cache
        target: /home/mcu/.terraform.d/plugin-cache
    user: mcu
    environment:
      OS_CLIENT_CONFIG_FILE: /home/mcu/credentials/clouds.yaml
      MAGIC_CASTLE_ACME_KEY_PEM: /home/mcu/credentials/acme_key.pem

  cleanup:
    build:
      context: .
      target: cleanup-daemon
    environment:
      - MCHUB_HOST=api
      - MCHUB_PORT=5000
    volumes:
      - type: bind
        source: ./run/configuration.json
        target: /home/mcu/configuration.json
        read_only: true

volumes:
  database:
  terraform-plugin-cache:
